### ISSUE TITLE
旋转是否可以从fui文件中知道是顺时针还是逆时针旋转

### ISSUE THREAD

**Issue by svatyvabin** [krapnikkk/fgui-restore#1]
我看到 test 中包含了旋转的文件，都是顺时针旋转的（单张图片顺时针旋转放到雪碧图中）。

但是如果遇到逆时针旋转的图片，出来的图就是错的：

![image](https://user-images.githubusercontent.com/8802439/126021646-6ba8b2f5-7337-44e9-8959-01e30ddaa049.png)

代码改为逆时针旋转则可以：
![image](https://user-images.githubusercontent.com/8802439/126021663-9be60478-9bc7-4cfa-926c-bab9e1b0f638.png)

原始雪碧图：
![Task_atlas0](https://user-images.githubusercontent.com/8802439/126021683-cc5d7129-597e-41c0-b720-78f5a8fb4e89.png)

测试文件：[Task_fui.zip](https://github.com/krapnikkk/fgui-restore/files/6833973/Task_fui.zip)

然后我看了 rotated 字段二进制数据的值，也只是 0 和 1，不存在其他值。

**Comment by krapnikkk** [comment]
已修复
